# -*- coding: utf-8 -*-
"""tarnava_50x50_data_process.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eNYqlJTeGSf7uQ2yaChgRQ-Mg4VtHnH1

# Târnava Valley 50×50 Patch Experiment - Data Processing

This notebook implements the data preparation workflow for the patch-based land-cover classification experiment conducted in the Târnava Valley, Romania. It loads the datasets exported from Google Earth Engine, reconstructs the spatial and temporal structure of the Sentinel-2 observations, verifies data integrity, and prepares standardized inputs for subsequent machine-learning experiments.

The main objectives are to:

- identify and validate the available metadata, label, and Sentinel-2 files;
- parse the exported TFRecord datasets;
- reconstruct the 50 × 50-pixel Sentinel-2 patches for each acquisition date;
- combine monthly and recovery exports without introducing duplicate observations;
- calculate spectral indices from the exported Sentinel-2 bands;
- evaluate missing-data patterns and valid-pixel coverage;
- organize observations into chronological patch-level time series;
- generate cached .npz datasets for subsequent CNN, recurrent, and continuous-time neural models, including ConvLTC and Liquid Neural Networks.

The following datasets are expected in Google Drive:
- tarnava_50x50_2023_patch_metadata.csv
- tarnava_50x50_2023_patch_polygons.geojson
- tarnava_50x50_2023_worldcover_label_patches*.tfrecord*

Full split-month exports: tarnava_50x50_2023_s2_train_month_03*.tfrecord*.
Recovery group-month exports: tarnava_50x50_2023_s2_train_tree_month_04*.tfrecord*

The final output consists of validated and structured patch-level time series containing:
- Sentinel-2 spectral bands;
- calculated spectral indices;
- acquisition dates and temporal intervals;
- valid-pixel masks;
- ESA WorldCover reference labels;
- training, validation, and test split information;
- patch identifiers and spatial metadata.

## 1. Runtime setup

Configure environment. TensorFlow is used only to read TFRecords.
This part runs on CPU.
"""

import sys
import os
import glob
import json
import math
import random
from pathlib import Path
from collections import defaultdict, Counter

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import tensorflow as tf

print("Python:", sys.version)
print("TensorFlow:", tf.__version__)

"""## 2. Mount Google Drive and configure paths"""

from google.colab import drive

drive.mount('/content/drive')

BASE_DIR = Path('/content/drive/MyDrive/GEE_Tarnava_LNN')
PREFIX = 'tarnava_50x50_2023'

PATCH_SIZE = 50
NO_DATA_VALUE = -9999.0

S2_BANDS = ['B2', 'B3', 'B4', 'B8', 'B11']
INDEX_BANDS = ['NDVI', 'NDWI', 'NDBI', 'NDMI']
ALL_FEATURE_BANDS = S2_BANDS + INDEX_BANDS

SPLITS = ['train', 'valid', 'test']
PATCH_GROUPS = ['tree', 'grassland', 'cropland', 'urban_mixed']
MONTHS = list(range(3, 12))

CLASS_ID_TO_NAME = {
    0: 'Tree cover',
    1: 'Shrubland',
    2: 'Grassland',
    3: 'Cropland',
    4: 'Built-up',
    255: 'Ignore / other'
}

WC_CODE_TO_NAME = {
    10: 'Tree cover',
    20: 'Shrubland',
    30: 'Grassland',
    40: 'Cropland',
    50: 'Built-up'
}

print('Base dir exists:', BASE_DIR.exists())
print('Base dir:', BASE_DIR)

"""## 3. Discover exported files

Checks the available files in Drive.
"""

def find_files(pattern):
    return sorted(str(p) for p in BASE_DIR.glob(pattern))

metadata_files = find_files(f'{PREFIX}_patch_metadata*.csv')
polygon_files = find_files(f'{PREFIX}_patch_polygons*.geojson')
label_files = find_files(f'{PREFIX}_worldcover_label_patches*.tfrecord*')

print('Metadata files:', metadata_files)
print('Polygon files:', polygon_files)
print('Label TFRecord files:', label_files)

# Sentinel-2 file discovery supports both full split-month files and recovery group-month files.
def discover_s2_files():
    records = []
    for split in SPLITS:
        for month in MONTHS:
            month_str = f'{month:02d}'
            full_pattern = f'{PREFIX}_s2_{split}_month_{month_str}*.tfrecord*'
            full_files = find_files(full_pattern)

            group_files = {}
            for group in PATCH_GROUPS:
                group_pattern = f'{PREFIX}_s2_{split}_{group}_month_{month_str}*.tfrecord*'
                files = find_files(group_pattern)
                if files:
                    group_files[group] = files

            if full_files:
                status = 'full_split_month'
                n_files = len(full_files)
            elif len(group_files) == len(PATCH_GROUPS):
                status = 'complete_group_month'
                n_files = sum(len(v) for v in group_files.values())
            elif group_files:
                status = 'partial_group_month'
                n_files = sum(len(v) for v in group_files.values())
            else:
                status = 'missing'
                n_files = 0

            records.append({
                'split': split,
                'month': month,
                'status': status,
                'n_files': n_files,
                'full_files': full_files,
                'group_files': group_files
            })
    return pd.DataFrame(records)

s2_status = discover_s2_files()
status_view = s2_status[['split', 'month', 'status', 'n_files']]
display(status_view)
print(status_view['status'].value_counts())

"""## 4. Read patch metadata

The expected design is 120 training patches, 30 validation patches, and 30 independent test patches. The patch groups are intentionally balanced:
- tree
- grassland
- cropland
- urban_mixed = built-up
"""

if not metadata_files:
    raise FileNotFoundError('No patch metadata CSV found yet. Wait for metadata export or check BASE_DIR/PREFIX.')

metadata_path = metadata_files[0]
patch_meta = pd.read_csv(metadata_path)

print('Metadata path:', metadata_path)
print('Shape:', patch_meta.shape)
display(patch_meta.head())

print('\nCounts by split:')
display(patch_meta['split'].value_counts().rename_axis('split').reset_index(name='count'))

print('\nCounts by split and patch_group:')
display(pd.crosstab(patch_meta['split'], patch_meta['patch_group']))

print('\nDominant ESA classes:')
display(pd.crosstab(patch_meta['split'], patch_meta['dominant_class_name']))

"""## 5. TFRecord utilities

Defines functions for inspecting and decoding Earth Engine TFRecord files.

- inspects one record to identify its fields and data types;
- reads scalar metadata and flattened array properties;
- uses VarLenFeature because Earth Engine stores arrays as variable-length features;
- converts TensorFlow sparse values into NumPy arrays;
- decodes text fields such as patch_id, split, and date;
- prepares the arrays for reconstruction into 50 × 50 patches.
"""

def tfrecord_dataset(paths, compression_type=None):
    if isinstance(paths, (str, Path)):
        paths = [str(paths)]
    else:
        paths = [str(p) for p in paths]

    if compression_type is None:
        # Earth Engine sometimes writes .tfrecord, sometimes .tfrecord.gz.
        # Use GZIP only if all paths end with .gz.
        compression_type = 'GZIP' if all(str(p).endswith('.gz') for p in paths) else ''
    return tf.data.TFRecordDataset(paths, compression_type=compression_type)


def inspect_tfrecord(paths, max_records=1):
    ds = tfrecord_dataset(paths)
    out = []
    for i, raw in enumerate(ds.take(max_records)):
        ex = tf.train.Example()
        ex.ParseFromString(raw.numpy())
        rows = []
        for key, feat in sorted(ex.features.feature.items()):
            kind = feat.WhichOneof('kind')
            if kind == 'float_list':
                n = len(feat.float_list.value)
                preview = list(feat.float_list.value[:5])
            elif kind == 'int64_list':
                n = len(feat.int64_list.value)
                preview = list(feat.int64_list.value[:5])
            elif kind == 'bytes_list':
                n = len(feat.bytes_list.value)
                preview = [v[:50] for v in feat.bytes_list.value[:3]]
            else:
                n = 0
                preview = []
            rows.append({'key': key, 'kind': kind, 'length': n, 'preview': preview})
        out.append(pd.DataFrame(rows))
    return out[0] if out else pd.DataFrame()


def get_example_count(paths):
    count = 0
    for _ in tfrecord_dataset(paths):
        count += 1
    return count

"""## 6. Inspect label TFRecord schema

Verifies the structure and record count of the ESA WorldCover label TFRecord. Each record should contain a 50 × 50 label_id array, while esa_label may also store the original WorldCover class codes.


- validate label structure
"""

if not label_files:
    print('No label TFRecords found yet. Skip this cell until label export is complete.')
else:
    label_schema = inspect_tfrecord(label_files[:1])
    display(label_schema)
    print('Number of label records:', get_example_count(label_files))

"""## 7. Parse label patches

Converts the flattened TFRecord labels into 50 × 50 NumPy arrays indexed by patch_id and summarizes the pixel-level class composition of each patch.

This creates a dictionary:
```python
labels_by_patch[patch_id] = np.array with shape [50, 50]
```
"""

LABEL_STRING_KEYS = ['patch_id', 'split', 'region_name', 'patch_group', 'dominant_class_name']
LABEL_NUMERIC_KEYS = [
    'center_lon', 'center_lat', 'inside_fraction',
    'tree_pixel_count', 'shrub_pixel_count', 'grass_pixel_count', 'crop_pixel_count', 'built_pixel_count',
    'ignored_pixel_count', 'selected_pixel_count', 'total_pixel_count',
    'tree_fraction', 'shrub_fraction', 'grass_fraction', 'crop_fraction', 'built_fraction', 'selected_fraction',
    'dominant_id', 'dominant_esa_code', 'dominant_fraction'
]


def sparse_first(parsed, key, default=None):
    if key not in parsed:
        return default
    dense = tf.sparse.to_dense(parsed[key])
    if dense.shape[0] == 0:
        return default
    return dense[0]


def bytes_to_str(x):
    if x is None:
        return None
    if isinstance(x, bytes):
        return x.decode('utf-8')
    if hasattr(x, 'numpy'):
        v = x.numpy()
        if isinstance(v, bytes):
            return v.decode('utf-8')
        return str(v)
    return str(x)


def parse_label_example(raw):
    feature_spec = {
        'label_id': tf.io.VarLenFeature(tf.float32),
        'esa_label': tf.io.VarLenFeature(tf.float32),
    }
    for k in LABEL_STRING_KEYS:
        feature_spec[k] = tf.io.VarLenFeature(tf.string)
    for k in LABEL_NUMERIC_KEYS:
        feature_spec[k] = tf.io.VarLenFeature(tf.float32)

    parsed = tf.io.parse_single_example(raw, feature_spec)

    patch_id = bytes_to_str(sparse_first(parsed, 'patch_id'))
    split = bytes_to_str(sparse_first(parsed, 'split'))
    patch_group = bytes_to_str(sparse_first(parsed, 'patch_group'))

    label_vec = tf.sparse.to_dense(parsed['label_id']).numpy()
    if label_vec.size != PATCH_SIZE * PATCH_SIZE:
        raise ValueError(f'Unexpected label_id length for {patch_id}: {label_vec.size}')

    label_arr = label_vec.reshape(PATCH_SIZE, PATCH_SIZE).astype(np.int16)

    item = {
        'patch_id': patch_id,
        'split': split,
        'patch_group': patch_group,
        'label_id': label_arr,
    }

    if 'esa_label' in parsed:
        esa_vec = tf.sparse.to_dense(parsed['esa_label']).numpy()
        if esa_vec.size == PATCH_SIZE * PATCH_SIZE:
            item['esa_label'] = esa_vec.reshape(PATCH_SIZE, PATCH_SIZE).astype(np.int16)

    return item


def load_label_patches(label_paths):
    labels_by_patch = {}
    label_records = []
    for raw in tfrecord_dataset(label_paths):
        item = parse_label_example(raw)
        labels_by_patch[item['patch_id']] = item['label_id']
        unique, counts = np.unique(item['label_id'], return_counts=True)
        label_records.append({
            'patch_id': item['patch_id'],
            'split': item['split'],
            'patch_group': item['patch_group'],
            'unique_labels': dict(zip(unique.tolist(), counts.tolist()))
        })
    return labels_by_patch, pd.DataFrame(label_records)

if label_files:
    labels_by_patch, label_records = load_label_patches(label_files)
    print('Loaded label patches:', len(labels_by_patch))
    display(label_records.head())
else:
    labels_by_patch, label_records = {}, pd.DataFrame()

"""## 8. Verify label reconstruction - visual check

Displays one reconstructed 50 × 50 label patch to verify its dimensions, class values, and spatial organization.
"""

if labels_by_patch:
    example_patch_id = next(iter(labels_by_patch.keys()))
    y = labels_by_patch[example_patch_id]

    plt.figure(figsize=(5, 5))
    plt.imshow(y, vmin=0, vmax=4)
    plt.title(f'Label patch: {example_patch_id}')
    plt.axis('off')
    plt.colorbar(label='label_id')
    plt.show()

    print('Shape:', y.shape)
    print('Unique values:', dict(zip(*np.unique(y, return_counts=True))))
else:
    print('No label patches loaded yet.')

"""## 9. Select Sentinel-2 source files

Selects one complete data source for each split and month, using either a single full export or four recovery files grouped by patch category.
"""

def files_for_split_month(split, month):
    month_str = f'{month:02d}'
    full_files = find_files(f'{PREFIX}_s2_{split}_month_{month_str}*.tfrecord*')
    if full_files:
        return full_files, 'full_split_month'

    group_files = []
    missing_groups = []
    for group in PATCH_GROUPS:
        files = find_files(f'{PREFIX}_s2_{split}_{group}_month_{month_str}*.tfrecord*')
        if files:
            group_files.extend(files)
        else:
            missing_groups.append(group)

    if group_files and not missing_groups:
        return sorted(group_files), 'complete_group_month'
    if group_files:
        return sorted(group_files), f'partial_group_month_missing_{missing_groups}'
    return [], 'missing'


def collect_available_s2_files():
    rows = []
    paths = []
    for split in SPLITS:
        for month in MONTHS:
            files, mode = files_for_split_month(split, month)
            rows.append({'split': split, 'month': month, 'mode': mode, 'n_files': len(files)})
            paths.extend(files)
    return pd.DataFrame(rows), sorted(set(paths))

s2_file_table, s2_all_files = collect_available_s2_files()
display(s2_file_table)
print('Total S2 TFRecord files currently available:', len(s2_all_files))

"""## 10. Inspect Sentinel-2 TFRecord schema

Verifies that each Sentinel-2 record contains five flattened 50 × 50 spectral-band arrays together with patch and acquisition metadata.
"""

if not s2_all_files:
    print('No Sentinel-2 TFRecords found yet. Wait for S2 exports.')
else:
    print('Inspecting:', s2_all_files[0])
    s2_schema = inspect_tfrecord([s2_all_files[0]])
    display(s2_schema)
    print('Example count in first S2 file:', get_example_count([s2_all_files[0]]))

"""## 11. Parse Sentinel-2 patches and compute spectral indices

Reconstructs the five exported Sentinel-2 bands as 50 × 50 arrays, identifies valid pixels, computes four spectral indices, and combines all features into a nine-channel patch.

The GEE export stores only B2, B3, B4, B8, and B11 as 50×50 arrays. The spectral indices are computed here:

- NDVI = (B8 − B4) / (B8 + B4)
- NDWI = (B3 − B8) / (B3 + B8)
- NDBI = (B11 − B8) / (B11 + B8)
- NDMI = (B8 − B11) / (B8 + B11)
"""

S2_STRING_KEYS = ['patch_id', 'split', 'region_name', 'patch_group', 'dominant_class_name', 'date', 's2_id']
S2_NUMERIC_KEYS = [
    'center_lon', 'center_lat', 'inside_fraction',
    'tree_pixel_count', 'shrub_pixel_count', 'grass_pixel_count', 'crop_pixel_count', 'built_pixel_count',
    'ignored_pixel_count', 'selected_pixel_count', 'total_pixel_count',
    'tree_fraction', 'shrub_fraction', 'grass_fraction', 'crop_fraction', 'built_fraction', 'selected_fraction',
    'dominant_id', 'dominant_esa_code', 'dominant_fraction',
    'time_start', 'doy', 'month', 'cloud_pct'
]


def safe_divide(num, den, eps=1e-6):
    return num / (den + eps)


def compute_indices(arr5):
    # arr5 shape: [H, W, 5] in B2, B3, B4, B8, B11 order.
    b2 = arr5[..., 0]
    b3 = arr5[..., 1]
    b4 = arr5[..., 2]
    b8 = arr5[..., 3]
    b11 = arr5[..., 4]

    nodata_mask = np.any(arr5 == NO_DATA_VALUE, axis=-1)

    ndvi = safe_divide(b8 - b4, b8 + b4)
    ndwi = safe_divide(b3 - b8, b3 + b8)
    ndbi = safe_divide(b11 - b8, b11 + b8)
    ndmi = safe_divide(b8 - b11, b8 + b11)

    idx = np.stack([ndvi, ndwi, ndbi, ndmi], axis=-1).astype(np.float32)
    idx[nodata_mask] = NO_DATA_VALUE
    return idx


def parse_s2_example(raw):
    feature_spec = {}
    for b in S2_BANDS:
        feature_spec[b] = tf.io.VarLenFeature(tf.float32)
    for k in S2_STRING_KEYS:
        feature_spec[k] = tf.io.VarLenFeature(tf.string)
    for k in S2_NUMERIC_KEYS:
        feature_spec[k] = tf.io.VarLenFeature(tf.float32)

    parsed = tf.io.parse_single_example(raw, feature_spec)

    item = {}
    for k in S2_STRING_KEYS:
        item[k] = bytes_to_str(sparse_first(parsed, k))
    for k in S2_NUMERIC_KEYS:
        v = sparse_first(parsed, k)
        item[k] = float(v.numpy()) if v is not None else np.nan

    band_arrays = []
    for band in S2_BANDS:
        vec = tf.sparse.to_dense(parsed[band]).numpy()
        if vec.size != PATCH_SIZE * PATCH_SIZE:
            raise ValueError(f'Unexpected {band} length for {item.get("patch_id")}: {vec.size}')
        band_arrays.append(vec.reshape(PATCH_SIZE, PATCH_SIZE).astype(np.float32))

    arr5 = np.stack(band_arrays, axis=-1)  # [H, W, 5]
    valid_mask = np.all(arr5 != NO_DATA_VALUE, axis=-1)
    valid_fraction = float(valid_mask.mean())

    idx = compute_indices(arr5)
    arr9 = np.concatenate([arr5, idx], axis=-1).astype(np.float32)

    item['array_5band'] = arr5
    item['array_9band'] = arr9
    item['valid_mask'] = valid_mask
    item['valid_fraction_colab'] = valid_fraction
    return item

"""## 12. Validate parsed Sentinel-2 samples

Reads several Sentinel-2 records and compares a valid RGB reconstruction with its corresponding 50 × 50 ESA WorldCover label map.
"""

def read_s2_sample(paths, n=3):
    items = []
    for raw in tfrecord_dataset(paths).take(n):
        items.append(parse_s2_example(raw))
    return items

if not s2_all_files:
    print('No S2 files available yet.')
else:
    sample_items = read_s2_sample([s2_all_files[0]], n=3)
    print('Loaded examples:', len(sample_items))
    for item in sample_items:
        print({
            'patch_id': item['patch_id'],
            'split': item['split'],
            'patch_group': item['patch_group'],
            'date': item['date'],
            'month': item['month'],
            'valid_fraction_colab': round(item['valid_fraction_colab'], 3),
            'array_5band_shape': item['array_5band'].shape,
            'array_9band_shape': item['array_9band'].shape,
        })

# if 'sample_items' in globals() and sample_items:
#     item = sample_items[0]

# if 'sample_items' in globals() and sample_items:
#     valid_items = [
#         x for x in sample_items
#         if x['valid_fraction_colab'] >= 0.20
#     ]
#     item = valid_items[0]

if 'sample_items' in globals() and sample_items:
    item = max(
        sample_items,
        key=lambda x: x['valid_fraction_colab']
    )

    arr = item['array_5band']

    # RGB = B4, B3, B2 = indices 2, 1, 0
    rgb = arr[..., [2, 1, 0]].copy()
    rgb[rgb == NO_DATA_VALUE] = np.nan
    rgb = np.clip(rgb / 0.3, 0, 1)
    rgb = np.nan_to_num(rgb, nan=0.0)

    fig, axes = plt.subplots(1, 2, figsize=(10, 4))
    axes[0].imshow(rgb)
    axes[0].set_title(
      f"S2 RGB\n{item['patch_id']} | {item['date']} | "
      f"valid={item['valid_fraction_colab']:.1%}")
    axes[0].axis('off')

    if labels_by_patch and item['patch_id'] in labels_by_patch:
        axes[1].imshow(labels_by_patch[item['patch_id']], vmin=0, vmax=4)
        axes[1].set_title('ESA label_id')
        axes[1].axis('off')
    else:
        axes[1].text(0.5, 0.5, 'Label not loaded/found', ha='center', va='center')
        axes[1].axis('off')

    plt.tight_layout()
    plt.show()

"""## 13. Build an example of Sentinel-2 record manifest

Scans the selected Sentinel-2 TFRecords and creates a compact index containing record locations, acquisition metadata, and valid-pixel fractions without retaining the full image arrays.
"""

def build_s2_manifest(max_files=None):
    files = s2_all_files[:max_files] if max_files else s2_all_files
    rows = []

    for file_i, path in enumerate(files, start=1):
        print(f'[{file_i}/{len(files)}] scanning {Path(path).name}')
        for rec_i, raw in enumerate(tfrecord_dataset([path])):
            item = parse_s2_example(raw)
            rows.append({
                'file_path': path,
                'record_index': rec_i,
                'patch_id': item['patch_id'],
                'split': item['split'],
                'patch_group': item['patch_group'],
                'date': item['date'],
                'time_start': item['time_start'],
                'doy': item['doy'],
                'month': int(item['month']) if not np.isnan(item['month']) else None,
                's2_id': item['s2_id'],
                'cloud_pct': item['cloud_pct'],
                'valid_fraction_colab': item['valid_fraction_colab'],
            })

    return pd.DataFrame(rows)

# Start with a quick scan of only 1-2 files while exports are still running.
# Later set max_files=None.
if s2_all_files:
    manifest_preview = build_s2_manifest(max_files=min(2, len(s2_all_files)))
    display(manifest_preview.head())
    print('Rows scanned:', len(manifest_preview))
else:
    manifest_preview = pd.DataFrame()
    print('No S2 files to scan yet.')

"""## 14.0 Setup"""

MIN_VALID_FRACTION = 0.20
MIN_OBSERVATIONS_PER_PATCH = 8
MIN_MONTHS_PER_PATCH = 6
MAX_GAP_DAYS_WARNING = 60

"""## 14. Build the complete Sentinel-2 manifest

Scans all selected Sentinel-2 TFRecords and saves a compact record-level index containing file location, patch identity, acquisition date, and valid-pixel coverage. The manifest supports completeness checks, duplicate removal, and quality filtering before tensor construction.
"""

RUN_FULL_MANIFEST_SCAN = False

CACHE_DIR = BASE_DIR / 'colab_cache'
CACHE_DIR.mkdir(exist_ok=True)
MANIFEST_PATH = CACHE_DIR / f'{PREFIX}_s2_manifest.csv'

if RUN_FULL_MANIFEST_SCAN:
    s2_manifest = build_s2_manifest(max_files=None)
    s2_manifest.to_csv(MANIFEST_PATH, index=False)
    print('Saved manifest:', MANIFEST_PATH)
else:
    if MANIFEST_PATH.exists():
        s2_manifest = pd.read_csv(MANIFEST_PATH)
        print('Loaded existing manifest:', MANIFEST_PATH)
    else:
        s2_manifest = manifest_preview.copy()
        print('Using manifest_preview. Set RUN_FULL_MANIFEST_SCAN=True later.')

if not s2_manifest.empty:
    display(s2_manifest.head())
    print('Manifest rows:', len(s2_manifest))
    print('Unique patches:', s2_manifest['patch_id'].nunique())
    print('Unique dates:', s2_manifest['date'].nunique())
    display(pd.crosstab(s2_manifest['split'], s2_manifest['month']))

"""## 15. Validate temporal coverage and data quality

Filters observations by valid-pixel coverage, retains the best record for each patch and acquisition date, and summarizes temporal coverage for every patch. The checks identify patches with sufficient usable observations and seasonal coverage for model training.
"""

# if not s2_manifest.empty:
#     obs_per_patch = s2_manifest.groupby(['split', 'patch_id']).size().reset_index(name='n_observations')
#     display(obs_per_patch.groupby('split')['n_observations'].describe())

#     valid_summary = s2_manifest.groupby(['split', 'month'])['valid_fraction_colab'].agg(['count', 'mean', 'min', 'max']).reset_index()
#     display(valid_summary)

#     plt.figure(figsize=(12, 5))
#     for split in SPLITS:
#         vals = obs_per_patch.loc[obs_per_patch['split'] == split, 'n_observations']
#         if len(vals):
#             plt.hist(vals, alpha=0.5, label=split)
#     plt.xlabel('Number of S2 records per patch')
#     plt.ylabel('Patch count')
#     plt.title('Temporal observation count per patch')
#     plt.legend()
#     plt.show()
# else:
#     print('No manifest data available yet.')

if not s2_manifest.empty:
    manifest_qc = s2_manifest.copy()
    manifest_qc['date'] = pd.to_datetime(manifest_qc['date'])

    # Retain sufficiently valid observations.
    manifest_qc = manifest_qc[
        manifest_qc['valid_fraction_colab'] >= MIN_VALID_FRACTION
    ].copy()

    # Keep the best observation when several records exist
    # for the same patch and acquisition date.
    manifest_qc = (
        manifest_qc
        .sort_values('valid_fraction_colab')
        .drop_duplicates(
            subset=['split', 'patch_id', 'date'],
            keep='last'
        )
    )

    def calculate_max_gap(date_series):
        dates = np.sort(pd.to_datetime(date_series).unique())

        if len(dates) < 2:
            return 0

        gaps = np.diff(dates).astype('timedelta64[D]').astype(int)
        return int(gaps.max())

    coverage = (
        manifest_qc
        .groupby(['split', 'patch_id'])
        .agg(
            n_observations=('date', 'nunique'),
            n_months=('month', 'nunique'),
            mean_valid_fraction=('valid_fraction_colab', 'mean'),
            min_valid_fraction=('valid_fraction_colab', 'min'),
            first_date=('date', 'min'),
            last_date=('date', 'max')
        )
        .reset_index()
    )

    gap_summary = (
        manifest_qc
        .groupby(['split', 'patch_id'])['date']
        .apply(calculate_max_gap)
        .reset_index(name='max_gap_days')
    )

    coverage = coverage.merge(
        gap_summary,
        on=['split', 'patch_id'],
        how='left'
    )

    # Include patches that have no usable observations.
    coverage = (
        patch_meta[['patch_id', 'split', 'patch_group']]
        .merge(
            coverage,
            on=['patch_id', 'split'],
            how='left'
        )
    )

    coverage['n_observations'] = (
        coverage['n_observations'].fillna(0).astype(int)
    )
    coverage['n_months'] = coverage['n_months'].fillna(0).astype(int)
    coverage['max_gap_days'] = coverage['max_gap_days'].fillna(0).astype(int)

    coverage['eligible'] = (
        (coverage['n_observations'] >= MIN_OBSERVATIONS_PER_PATCH) &
        (coverage['n_months'] >= MIN_MONTHS_PER_PATCH)
    )

    print('Quality threshold:', MIN_VALID_FRACTION)
    print('Eligible patches:', int(coverage['eligible'].sum()))
    print('Excluded patches:', int((~coverage['eligible']).sum()))

    display(
        coverage
        .groupby('split')[
            ['n_observations', 'n_months', 'max_gap_days']
        ]
        .describe()
    )

    print('\nEligible patches by split and patch group:')
    display(
        pd.crosstab(
            coverage['split'],
            coverage['patch_group'],
            values=coverage['eligible'].astype(int),
            aggfunc='sum'
        ).fillna(0).astype(int)
    )

    print('\nPatches with temporal gaps above warning threshold:')
    display(
        coverage[
            coverage['max_gap_days'] > MAX_GAP_DAYS_WARNING
        ].sort_values('max_gap_days', ascending=False)
    )

    quality_patch_ids = {
        split: set(
            coverage.loc[
                (coverage['split'] == split) &
                coverage['eligible'],
                'patch_id'
            ]
        )
        for split in SPLITS
    }

    plt.figure(figsize=(12, 5))

    for split in SPLITS:
        values = coverage.loc[
            coverage['split'] == split,
            'n_observations'
        ]

        if len(values):
            plt.hist(values, alpha=0.5, label=split)

    plt.axvline(
        MIN_OBSERVATIONS_PER_PATCH,
        linestyle='--',
        label='minimum required'
    )
    plt.xlabel('Usable observations per patch')
    plt.ylabel('Patch count')
    plt.title('Quality-controlled temporal coverage')
    plt.legend()
    plt.show()

else:
    manifest_qc = pd.DataFrame()
    coverage = pd.DataFrame()
    quality_patch_ids = {}
    print('No manifest data available.')

# part 2
def summarize_label_pixels(patch_ids):
    counts = Counter()

    for patch_id in patch_ids:
        label = labels_by_patch.get(patch_id)

        if label is None:
            continue

        values, frequencies = np.unique(label, return_counts=True)

        for value, frequency in zip(values, frequencies):
            counts[int(value)] += int(frequency)

    return counts


label_support_rows = []

for split in SPLITS:
    patch_ids = quality_patch_ids.get(split, set())
    counts = summarize_label_pixels(patch_ids)

    total_valid = sum(
        count for class_id, count in counts.items()
        if class_id != 255
    )

    for class_id in [0, 1, 2, 3, 4, 255]:
        count = counts.get(class_id, 0)

        label_support_rows.append({
            'split': split,
            'class_id': class_id,
            'class_name': CLASS_ID_TO_NAME[class_id],
            'pixel_count': count,
            'fraction': (
                count / total_valid
                if total_valid and class_id != 255
                else np.nan
            )
        })

label_support = pd.DataFrame(label_support_rows)
display(label_support)

"""## 15.1 Define the final four-class target map

Shrubland is excluded because it has insufficient reference pixels and is absent from the independent test set. The remaining ESA WorldCover labels are remapped to four contiguous model classes: Tree cover, Grassland, Cropland, and Built-up. Unsupported and other land-cover pixels are assigned the ignore value 255.
"""

# Final segmentation classes:
# 0 = Tree cover
# 1 = Grassland
# 2 = Cropland
# 3 = Built-up
# 255 = ignored pixels

TARGET_CLASS_ID_TO_NAME = {
    0: 'Tree cover',
    1: 'Grassland',
    2: 'Cropland',
    3: 'Built-up',
    255: 'Ignore / other'
}

N_CLASSES = 4


def remap_target_labels(label_array):
    remapped = np.full(
        label_array.shape,
        255,
        dtype=np.int16
    )

    remapped[label_array == 0] = 0  # Tree cover
    remapped[label_array == 2] = 1  # Grassland
    remapped[label_array == 3] = 2  # Cropland
    remapped[label_array == 4] = 3  # Built-up

    # Original class 1, Shrubland, remains 255.
    return remapped


labels_by_patch = {
    patch_id: remap_target_labels(label_array)
    for patch_id, label_array in labels_by_patch.items()
}

CLASS_ID_TO_NAME = TARGET_CLASS_ID_TO_NAME

print('Final number of target classes:', N_CLASSES)
print('Final target classes:', {
    class_id: class_name
    for class_id, class_name in CLASS_ID_TO_NAME.items()
    if class_id != 255
})


final_label_rows = []

for split in SPLITS:
    patch_ids = quality_patch_ids.get(split, set())
    counts = summarize_label_pixels(patch_ids)

    valid_total = sum(
        counts.get(class_id, 0)
        for class_id in range(N_CLASSES)
    )

    for class_id in range(N_CLASSES):
        count = counts.get(class_id, 0)

        final_label_rows.append({
            'split': split,
            'class_id': class_id,
            'class_name': CLASS_ID_TO_NAME[class_id],
            'pixel_count': count,
            'fraction': count / valid_total if valid_total else np.nan
        })

final_label_support = pd.DataFrame(final_label_rows)
display(final_label_support)

assert (
    final_label_support['pixel_count'] > 0
).all(), 'At least one target class is absent from a split.'

"""## 16. Build quality-controlled patch time-series tensors

Reconstructs chronological 50 × 50 Sentinel-2 sequences for each eligible patch and aligns them with the corresponding ESA WorldCover label map. Records below the valid-pixel threshold are excluded, while duplicate patch-date observations are resolved by retaining the record with the highest valid coverage.

The output contains spectral features, temporal masks, pixel-validity masks, acquisition intervals, labels, dates, and patch identifiers.

Output shape:

```python
X:      [N, T, 50, 50, 9]
y:      [N, 50, 50]
mask_t: [N, T]
delta:  [N, T, 1]
```
"""

def iter_s2_items_for_split(split, months=None):
    months = MONTHS if months is None else months
    for month in months:
        files, mode = files_for_split_month(split, month)
        for path in files:
            for raw in tfrecord_dataset([path]):
                item = parse_s2_example(raw)
                if item['split'] == split:
                    yield item


def build_split_tensor(
    split,
    months=None,
    patch_ids=None,
    min_valid_fraction=MIN_VALID_FRACTION,
    max_dates=None,
    max_patches=None,
):
    if not labels_by_patch:
        raise RuntimeError('Load label patches before building tensors.')

    months = MONTHS if months is None else months

    # Collect best item per patch_id + date.
    best = {}
    for item in iter_s2_items_for_split(split, months=months):
        pid = item['patch_id']
        if patch_ids is not None and pid not in patch_ids:
            continue
        if item['valid_fraction_colab'] < min_valid_fraction:
            continue
        key = (pid, item['date'])
        old = best.get(key)
        if old is None or item['valid_fraction_colab'] > old['valid_fraction_colab']:
            best[key] = item

    if not best:
        raise RuntimeError(f'No usable S2 records found for split={split}, months={months}')

    # Determine patch list and date list.
    patch_list = sorted({pid for pid, date in best.keys() if pid in labels_by_patch})
    if max_patches is not None:
        patch_list = patch_list[:max_patches]

    date_list = sorted({date for pid, date in best.keys() if pid in patch_list})
    if max_dates is not None:
        date_list = date_list[:max_dates]

    N = len(patch_list)
    T = len(date_list)
    H = W = PATCH_SIZE
    C = len(ALL_FEATURE_BANDS)

    X = np.zeros((N, T, H, W, C), dtype=np.float32)
    valid_pixel_mask = np.zeros((N, T, H, W), dtype=bool)
    time_mask = np.zeros((N, T), dtype=np.float32)
    observation_valid_fraction = np.zeros((N, T), dtype=np.float32)
    delta_days = np.zeros((N, T, 1), dtype=np.float32)
    y = np.zeros((N, H, W), dtype=np.int16)

    date_to_idx = {d: i for i, d in enumerate(date_list)}

    for i, pid in enumerate(patch_list):
        y[i] = labels_by_patch[pid]
        last_date = None
        for date in date_list:
            item = best.get((pid, date))
            if item is None:
                continue
            t = date_to_idx[date]
            arr = item['array_9band']
            X[i, t] = arr
            valid_pixel_mask[i, t] = np.all(arr[..., :5] != NO_DATA_VALUE, axis=-1)
            time_mask[i, t] = 1.0
            observation_valid_fraction[i, t] = item['valid_fraction_colab']

            current_date = pd.to_datetime(date)
            if last_date is None:
                delta_days[i, t, 0] = 0.0
            else:
                delta_days[i, t, 0] = (current_date - last_date).days
            last_date = current_date

    # Replace NO_DATA_VALUE with 0 after masks are stored.
    X[X == NO_DATA_VALUE] = 0.0
    n_observations = time_mask.sum(axis=1).astype(np.int16)

    return {
        'X': X,
        'y': y,
        'time_mask': time_mask,
        'valid_pixel_mask': valid_pixel_mask,
        'observation_valid_fraction': observation_valid_fraction,
        'delta_days': delta_days,
        'n_observations': n_observations,
        'patch_ids': np.array(patch_list),
        'dates': np.array(date_list),
        'bands': np.array(ALL_FEATURE_BANDS),
    }

# Small smoke test: one month, first few patches.
RUN_SMALL_TENSOR_TEST = False

if RUN_SMALL_TENSOR_TEST:
    train_small = build_split_tensor(
        split='train',
        months=[3],
        max_patches=4,
        max_dates=5
    )

    print('X:', train_small['X'].shape)
    print('y:', train_small['y'].shape)
    print('time_mask:', train_small['time_mask'].shape)
    print(
        'valid_pixel_mask:',
        train_small['valid_pixel_mask'].shape
    )
    print(
        'observation_valid_fraction:',
        train_small['observation_valid_fraction'].shape
    )
    print('delta_days:', train_small['delta_days'].shape)
    print(
        'n_observations:',
        train_small['n_observations']
    )
    print('patch_ids:', train_small['patch_ids'])
    print('dates:', train_small['dates'])
    print(
        'Unique target labels:',
        np.unique(train_small['y'])
    )
    print(
        'Finite X values:',
        np.isfinite(train_small['X']).all()
    )

"""## 17. Save tensors to NPZ cache

Builds and saves quality-controlled Sentinel-2 tensors for the training validation, and test splits. Each cache contains the spectral time series, ESA WorldCover labels, temporal masks, valid-pixel masks, acquisition intervals, observation-quality values, dates, and patch identifiers.

First run:
RUN_SAVE_SMALL_CACHE = True,
RUN_SAVE_FULL_CACHE = False.

After successful run:
RUN_SAVE_SMALL_CACHE = False,
RUN_SAVE_FULL_CACHE = True
"""

RUN_SAVE_SMALL_CACHE = False
RUN_SAVE_FULL_CACHE = False


def save_tensor_cache(
    split,
    months,
    suffix,
    apply_quality_filter=True
):
    """
    Build and save one model-ready dataset split.
    """

    selected_patch_ids = None

    if apply_quality_filter:
        if 'quality_patch_ids' not in globals():
            raise RuntimeError(
                'Run Section 15 before saving quality-controlled caches.'
            )

        selected_patch_ids = quality_patch_ids.get(split, set())

        if not selected_patch_ids:
            raise RuntimeError(
                f'No eligible patches found for split={split}.'
            )

    data = build_split_tensor(
        split=split,
        months=months,
        patch_ids=selected_patch_ids,
        min_valid_fraction=MIN_VALID_FRACTION
    )

    out_path = CACHE_DIR / f'{PREFIX}_{split}_{suffix}.npz'

    np.savez_compressed(
        out_path,
        X=data['X'],
        y=data['y'],
        time_mask=data['time_mask'],
        valid_pixel_mask=data['valid_pixel_mask'],
        observation_valid_fraction=data[
            'observation_valid_fraction'
        ],
        delta_days=data['delta_days'],
        n_observations=data['n_observations'],
        patch_ids=data['patch_ids'],
        dates=data['dates'],
        bands=data['bands'],
        split=np.array(split),
        months=np.array(months, dtype=np.int16),
        min_valid_fraction=np.array(
            MIN_VALID_FRACTION,
            dtype=np.float32
        )
    )

    print('Saved:', out_path)
    print('X:', data['X'].shape)
    print('y:', data['y'].shape)
    print('time_mask:', data['time_mask'].shape)
    print('valid_pixel_mask:', data['valid_pixel_mask'].shape)
    print('Patches:', len(data['patch_ids']))
    print('Dates:', len(data['dates']))
    print(
        'Usable observations per patch:',
        data['n_observations'].min(),
        '-',
        data['n_observations'].max()
    )

    return out_path


# Small cache test: March training data.
if RUN_SAVE_SMALL_CACHE:
    save_tensor_cache(
        split='train',
        months=[3],
        suffix='month03_test',
        apply_quality_filter=True
    )


# Final March-November caches.
if RUN_SAVE_FULL_CACHE:
    saved_cache_paths = {}

    for split in SPLITS:
        saved_cache_paths[split] = save_tensor_cache(
            split=split,
            months=MONTHS,
            suffix='mar_nov_full',
            apply_quality_filter=True
        )

    print('\nCompleted cache files:')

    for split, path in saved_cache_paths.items():
        print(f'{split}: {path}')

"""## 18. Load cached datasets for PyTorch

Loads a model-ready `.npz` cache as a PyTorch Dataset. Each sample contains a chronological Sentinel-2 sequence, the corresponding 50 × 50 ESA WorldCover label map, temporal and pixel-validity masks, acquisition intervals, observation-quality values, and patch metadata.

The Sentinel-2 tensor is returned in channel-first format:

```python
X: [T, 9, 50, 50]
y: [50, 50]
```
"""

import torch
from torch.utils.data import Dataset, DataLoader


class TarnavaPatchTimeSeriesDataset(Dataset):
    def __init__(self, npz_path):
        data = np.load(npz_path, allow_pickle=False)

        # Stored cache shape: [N, T, H, W, C]
        self.X = torch.from_numpy(
            data['X'].astype(np.float32, copy=False)
        )

        # Pixel-level ESA WorldCover labels: [N, H, W]
        self.y = torch.from_numpy(
            data['y'].astype(np.int64, copy=False)
        )

        self.time_mask = torch.from_numpy(
            data['time_mask'].astype(np.float32, copy=False)
        )

        self.valid_pixel_mask = torch.from_numpy(
            data['valid_pixel_mask'].astype(bool, copy=False)
        )

        self.delta_days = torch.from_numpy(
            data['delta_days'].astype(np.float32, copy=False)
        )

        if 'observation_valid_fraction' in data.files:
            self.observation_valid_fraction = torch.from_numpy(
                data['observation_valid_fraction'].astype(
                    np.float32,
                    copy=False
                )
            )
        else:
            self.observation_valid_fraction = self.time_mask.clone()

        if 'n_observations' in data.files:
            self.n_observations = torch.from_numpy(
                data['n_observations'].astype(
                    np.int64,
                    copy=False
                )
            )
        else:
            self.n_observations = self.time_mask.sum(dim=1).long()

        self.patch_ids = data['patch_ids']
        self.dates = data['dates']
        self.bands = data['bands']

    def __len__(self):
        return self.X.shape[0]

    def __getitem__(self, idx):
        # Convert [T, H, W, C] to [T, C, H, W].
        x = self.X[idx].permute(0, 3, 1, 2)

        y = self.y[idx]

        return {
            'X': x,
            'y': y,

            # Exclude unsupported WorldCover pixels from the loss.
            'label_mask': y != 255,

            # Available acquisition dates.
            'time_mask': self.time_mask[idx],

            # Valid pixels within each acquisition.
            'valid_pixel_mask': self.valid_pixel_mask[idx],

            # Fraction of valid pixels per acquisition.
            'observation_valid_fraction':
                self.observation_valid_fraction[idx],

            # Days since the previous usable acquisition.
            'delta_days': self.delta_days[idx],

            'n_observations': self.n_observations[idx],
            'patch_id': str(self.patch_ids[idx]),
        }


print('Dataset class ready.')

"""## 18.1 Verify"""

train_cache_path = (
    CACHE_DIR /
    f'{PREFIX}_train_mar_nov_full.npz'
)

train_dataset = TarnavaPatchTimeSeriesDataset(
    train_cache_path
)

sample = train_dataset[0]

print('Dataset length:', len(train_dataset))
print('X:', sample['X'].shape)
print('y:', sample['y'].shape)
print('time_mask:', sample['time_mask'].shape)
print(
    'valid_pixel_mask:',
    sample['valid_pixel_mask'].shape
)
print(
    'observation_valid_fraction:',
    sample['observation_valid_fraction'].shape
)
print('delta_days:', sample['delta_days'].shape)
print('n_observations:', sample['n_observations'].item())
print('patch_id:', sample['patch_id'])
print('Target labels:', torch.unique(sample['y']))
print('Finite X:', torch.isfinite(sample['X']).all().item())

"""## 18.2 Consistency check"""

assert sample['n_observations'].item() == int(
    sample['time_mask'].sum().item()
)

missing_dates = sample['time_mask'] == 0

assert torch.all(
    sample['observation_valid_fraction'][missing_dates] == 0
)

assert torch.all(
    sample['X'][missing_dates] == 0
)

assert sample['X'].shape[1] == 9
assert sample['y'].shape == (50, 50)

print('Final dataset consistency checks passed.')

"""## 19 - Prepare the 2024 temporal-transfer test dataset

This section prepares Sentinel-2 observations from March–November 2024 for the
same 30 geographically separated Region B patches used in the 2023 test set.

No training or validation data are created for 2024. The reference maps are reused
from the existing 2023 Region B cache to guarantee identical spatial targets across
the two evaluation years.

### 19.1 — Discover and verify all 2024 exports
"""

# -------------------------------------------------------
# 19.1 Discover 2024 Sentinel-2 Region B exports
# -------------------------------------------------------

PREFIX_2024 = 'tarnava_50x50_2024'
MONTHS_2024 = list(range(3, 12))

TEST_2023_CACHE_PATH = (
    CACHE_DIR /
    'tarnava_50x50_2023_test_mar_nov_full.npz'
)

TEST_2024_CACHE_PATH = (
    CACHE_DIR /
    'tarnava_50x50_2024_test_mar_nov_full.npz'
)


def files_for_2024_test_month(month):
    """
    Locate one complete 2024 test-month export.

    Supports:
    1. one full test-month TFRecord;
    2. four recovery files grouped by patch category.
    """

    month_str = f'{month:02d}'

    full_files = find_files(
        f'{PREFIX_2024}_s2_test_month_{month_str}*.tfrecord*'
    )

    if full_files:
        return full_files, 'full_test_month'

    group_files = []
    missing_groups = []

    for group in PATCH_GROUPS:
        files = find_files(
            f'{PREFIX_2024}_s2_test_{group}_month_{month_str}*.tfrecord*'
        )

        if files:
            group_files.extend(files)
        else:
            missing_groups.append(group)

    if group_files and not missing_groups:
        return sorted(group_files), 'complete_group_month'

    if group_files:
        return (
            sorted(group_files),
            f'partial_group_month_missing_{missing_groups}'
        )

    return [], 'missing'


status_rows = []
s2_2024_all_files = []

for month in MONTHS_2024:
    files, mode = files_for_2024_test_month(month)

    status_rows.append({
        'month': month,
        'mode': mode,
        'n_files': len(files)
    })

    s2_2024_all_files.extend(files)


s2_2024_status = pd.DataFrame(status_rows)

display(s2_2024_status)

print(
    '\nTotal 2024 TFRecord files:',
    len(s2_2024_all_files)
)

print(
    'Unique 2024 TFRecord files:',
    len(set(s2_2024_all_files))
)


complete_modes = {
    'full_test_month',
    'complete_group_month'
}

all_months_complete = (
    s2_2024_status['mode']
    .isin(complete_modes)
    .all()
)

print(
    '\nAll March-November 2024 months complete:',
    all_months_complete
)


assert TEST_2023_CACHE_PATH.exists(), (
    f'Missing 2023 Region B cache: {TEST_2023_CACHE_PATH}'
)

assert all_months_complete, (
    'At least one 2024 month is incomplete.'
)

print(
    '\n2024 export discovery passed.'
)

"""### 19.2 — Load the frozen 2023 Region B reference"""

# -------------------------------------------------------
# 19.2 Load the frozen Region B spatial reference
# -------------------------------------------------------

with np.load(
    TEST_2023_CACHE_PATH,
    allow_pickle=False
) as cache_2023:

    reference_patch_ids = (
        cache_2023['patch_ids']
        .astype(str)
    )

    reference_labels = (
        cache_2023['y']
        .astype(np.int16)
        .copy()
    )

    reference_bands = (
        cache_2023['bands']
        .astype(str)
    )


print(
    'Reference Region B patches:',
    len(reference_patch_ids)
)

print(
    'Reference label shape:',
    reference_labels.shape
)

print(
    'Reference bands:',
    reference_bands.tolist()
)

print(
    'Reference target values:',
    np.unique(reference_labels)
)


assert len(reference_patch_ids) == 30

assert len(
    np.unique(reference_patch_ids)
) == 30

assert reference_labels.shape == (
    30,
    PATCH_SIZE,
    PATCH_SIZE
)

assert set(
    np.unique(reference_labels).tolist()
).issubset({
    0, 1, 2, 3, 255
})

assert reference_bands.tolist() == ALL_FEATURE_BANDS


reference_label_by_patch = {
    patch_id: reference_labels[index]
    for index, patch_id
    in enumerate(reference_patch_ids)
}


print(
    '\nFrozen 2023 Region B reference loaded successfully.'
)

"""### 19.3 — Inspect one 2024 TFRecord before scanning everything"""

# -------------------------------------------------------
# 19.3 Inspect one 2024 Sentinel-2 TFRecord
# -------------------------------------------------------

first_2024_file = sorted(
    set(s2_2024_all_files)
)[0]

print(
    'Inspecting:',
    Path(first_2024_file).name
)

schema_2024 = inspect_tfrecord(
    [first_2024_file]
)

display(schema_2024)

print(
    '\nRecords in first 2024 file:',
    get_example_count(
        [first_2024_file]
    )
)


sample_2024 = read_s2_sample(
    [first_2024_file],
    n=3
)


for item in sample_2024:
    print({
        'patch_id':
            item['patch_id'],

        'split':
            item['split'],

        'patch_group':
            item['patch_group'],

        'date':
            item['date'],

        'month':
            item['month'],

        'valid_fraction':
            round(
                item['valid_fraction_colab'],
                4
            ),

        'array_5band_shape':
            item['array_5band'].shape,

        'array_9band_shape':
            item['array_9band'].shape,
    })

"""### 19.4 — Full 2024 manifest scan"""

# -------------------------------------------------------
# 19.4 Build complete 2024 manifest
# -------------------------------------------------------

MANIFEST_2024_PATH = (
    CACHE_DIR /
    f'{PREFIX_2024}_s2_manifest.csv'
)


def build_2024_test_manifest():
    rows = []

    files = sorted(
        set(s2_2024_all_files)
    )

    for file_index, path in enumerate(
        files,
        start=1
    ):

        print(
            f'[{file_index}/{len(files)}] '
            f'scanning {Path(path).name}'
        )

        for record_index, raw in enumerate(
            tfrecord_dataset([path])
        ):

            item = parse_s2_example(raw)

            rows.append({
                'file_path':
                    path,

                'record_index':
                    record_index,

                'patch_id':
                    item['patch_id'],

                'split':
                    item['split'],

                'patch_group':
                    item['patch_group'],

                'date':
                    item['date'],

                'time_start':
                    item['time_start'],

                'doy':
                    item['doy'],

                'month':
                    int(item['month']),

                's2_id':
                    item['s2_id'],

                'cloud_pct':
                    item['cloud_pct'],

                'valid_fraction_colab':
                    item[
                        'valid_fraction_colab'
                    ]
            })

    return pd.DataFrame(rows)


s2_manifest_2024 = (
    build_2024_test_manifest()
)


s2_manifest_2024.to_csv(
    MANIFEST_2024_PATH,
    index=False
)


print(
    '\nSaved:',
    MANIFEST_2024_PATH
)

print(
    'Manifest rows:',
    len(s2_manifest_2024)
)

print(
    'Unique patch IDs:',
    s2_manifest_2024[
        'patch_id'
    ].nunique()
)

print(
    'Unique dates:',
    s2_manifest_2024[
        'date'
    ].nunique()
)


display(
    pd.crosstab(
        s2_manifest_2024[
            'patch_group'
        ],
        s2_manifest_2024[
            'month'
        ]
    )
)

"""### 19.5 — Critical spatial and temporal validation"""

# -------------------------------------------------------
# 19.5 Validate 2024 Region B data
# -------------------------------------------------------

manifest_2024 = (
    s2_manifest_2024.copy()
)

manifest_2024['date'] = pd.to_datetime(
    manifest_2024['date']
)


# -------------------------------------------------------
# Basic metadata checks
# -------------------------------------------------------

observed_patch_ids = set(
    manifest_2024[
        'patch_id'
    ].astype(str)
)

expected_patch_ids = set(
    reference_patch_ids
)


missing_patch_ids = sorted(
    expected_patch_ids
    - observed_patch_ids
)

unexpected_patch_ids = sorted(
    observed_patch_ids
    - expected_patch_ids
)


print(
    'Expected Region B patches:',
    len(expected_patch_ids)
)

print(
    'Observed 2024 patches:',
    len(observed_patch_ids)
)

print(
    'Missing patch IDs:',
    missing_patch_ids
)

print(
    'Unexpected patch IDs:',
    unexpected_patch_ids
)


assert not missing_patch_ids
assert not unexpected_patch_ids

assert (
    manifest_2024['split']
    == 'test'
).all()

assert (
    manifest_2024['date']
    .dt.year
    == 2024
).all()

assert set(
    manifest_2024[
        'month'
    ].astype(int)
) == set(
    MONTHS_2024
)


# -------------------------------------------------------
# Apply same quality threshold as 2023
# -------------------------------------------------------

manifest_2024_qc = (
    manifest_2024[
        manifest_2024[
            'valid_fraction_colab'
        ]
        >= MIN_VALID_FRACTION
    ]
    .copy()
)


# Keep best observation for duplicate patch-date pairs.
manifest_2024_qc = (
    manifest_2024_qc
    .sort_values(
        'valid_fraction_colab'
    )
    .drop_duplicates(
        subset=[
            'patch_id',
            'date'
        ],
        keep='last'
    )
)


coverage_2024 = (
    manifest_2024_qc
    .groupby(
        'patch_id'
    )
    .agg(
        n_observations=(
            'date',
            'nunique'
        ),
        n_months=(
            'month',
            'nunique'
        ),
        first_date=(
            'date',
            'min'
        ),
        last_date=(
            'date',
            'max'
        ),
        mean_valid_fraction=(
            'valid_fraction_colab',
            'mean'
        ),
        min_valid_fraction=(
            'valid_fraction_colab',
            'min'
        )
    )
    .reset_index()
)


# Ensure even patches with zero usable records
# would be visible.
coverage_2024 = (
    pd.DataFrame({
        'patch_id':
            reference_patch_ids
    })
    .merge(
        coverage_2024,
        on='patch_id',
        how='left'
    )
)


coverage_2024[
    'n_observations'
] = (
    coverage_2024[
        'n_observations'
    ]
    .fillna(0)
    .astype(int)
)

coverage_2024[
    'n_months'
] = (
    coverage_2024[
        'n_months'
    ]
    .fillna(0)
    .astype(int)
)


display(
    coverage_2024
)


print(
    '\n2024 observation summary:'
)

display(
    coverage_2024[
        [
            'n_observations',
            'n_months',
            'mean_valid_fraction'
        ]
    ].describe()
)


print(
    '\nPatches below 2023 quality requirements:'
)

display(
    coverage_2024[
        (
            coverage_2024[
                'n_observations'
            ]
            < MIN_OBSERVATIONS_PER_PATCH
        )
        |
        (
            coverage_2024[
                'n_months'
            ]
            < MIN_MONTHS_PER_PATCH
        )
    ]
)


assert (
    coverage_2024[
        'n_observations'
    ] > 0
).all()


print(
    '\n2024 spatial and temporal validation passed.'
)

"""### 19.6 — Build and save the 2024 Region B tensor

Constructs the March–November 2024 Sentinel-2 time series for the exact 30
Region B patches used in the 2023 test set. The same 2023 ESA WorldCover
reference maps are reused, while Sentinel-2 observations are independently
quality filtered for 2024.

The cache structure is identical to the model-ready 2023 test cache.
"""

# -------------------------------------------------------
# 19.6 Build the complete 2024 Region B tensor
# -------------------------------------------------------

def iter_2024_test_items():
    """
    Yield all Sentinel-2 records from the complete
    March-November 2024 Region B exports.
    """

    for month in MONTHS_2024:

        files, mode = (
            files_for_2024_test_month(
                month
            )
        )

        if mode not in {
            'full_test_month',
            'complete_group_month'
        }:
            raise RuntimeError(
                f'Incomplete 2024 month {month}: {mode}'
            )

        for path in files:

            for raw in tfrecord_dataset(
                [path]
            ):

                item = parse_s2_example(
                    raw
                )

                if item['split'] != 'test':
                    raise RuntimeError(
                        'Unexpected split in 2024 export: '
                        f"{item['split']}"
                    )

                yield item


def build_2024_test_tensor(
    min_valid_fraction=MIN_VALID_FRACTION
):
    """
    Construct the complete 2024 Region B temporal-transfer
    dataset using the frozen 2023 Region B reference labels.
    """

    # ---------------------------------------------------
    # Keep the best observation for each patch + date
    # ---------------------------------------------------

    best = {}

    expected_patch_set = set(
        reference_patch_ids
    )

    for item in iter_2024_test_items():

        patch_id = item[
            'patch_id'
        ]

        if patch_id not in expected_patch_set:
            raise RuntimeError(
                'Unexpected 2024 patch ID: '
                f'{patch_id}'
            )

        if (
            item['valid_fraction_colab']
            < min_valid_fraction
        ):
            continue

        key = (
            patch_id,
            item['date']
        )

        old_item = best.get(
            key
        )

        if (
            old_item is None
            or
            item['valid_fraction_colab']
            >
            old_item['valid_fraction_colab']
        ):
            best[key] = item


    if not best:
        raise RuntimeError(
            'No usable 2024 observations found.'
        )


    # ---------------------------------------------------
    # Preserve exact 2023 Region B patch order
    # ---------------------------------------------------

    patch_list = (
        reference_patch_ids.tolist()
    )


    # Global temporal axis across the 30 patches.
    date_list = sorted({
        date
        for patch_id, date
        in best.keys()
    })


    N = len(
        patch_list
    )

    T = len(
        date_list
    )

    H = W = PATCH_SIZE

    C = len(
        ALL_FEATURE_BANDS
    )


    print(
        '2024 tensor dimensions:'
    )

    print(
        'N patches:',
        N
    )

    print(
        'T unique usable dates:',
        T
    )

    print(
        'Channels:',
        C
    )


    # ---------------------------------------------------
    # Allocate arrays
    # ---------------------------------------------------

    X = np.zeros(
        (
            N,
            T,
            H,
            W,
            C
        ),
        dtype=np.float32
    )

    y = (
        reference_labels
        .astype(
            np.int16,
            copy=True
        )
    )

    time_mask = np.zeros(
        (
            N,
            T
        ),
        dtype=np.float32
    )

    valid_pixel_mask = np.zeros(
        (
            N,
            T,
            H,
            W
        ),
        dtype=bool
    )

    observation_valid_fraction = (
        np.zeros(
            (
                N,
                T
            ),
            dtype=np.float32
        )
    )

    delta_days = np.zeros(
        (
            N,
            T,
            1
        ),
        dtype=np.float32
    )


    date_to_index = {
        date: index
        for index, date
        in enumerate(date_list)
    }


    # ---------------------------------------------------
    # Populate patch sequences
    # ---------------------------------------------------

    for patch_index, patch_id in enumerate(
        patch_list
    ):

        last_date = None

        patch_observation_count = 0


        for date in date_list:

            item = best.get(
                (
                    patch_id,
                    date
                )
            )

            if item is None:
                continue


            time_index = (
                date_to_index[
                    date
                ]
            )


            arr = item[
                'array_9band'
            ]


            if arr.shape != (
                PATCH_SIZE,
                PATCH_SIZE,
                len(
                    ALL_FEATURE_BANDS
                )
            ):
                raise RuntimeError(
                    'Unexpected 2024 array shape '
                    f'for {patch_id} on {date}: '
                    f'{arr.shape}'
                )


            X[
                patch_index,
                time_index
            ] = arr


            valid_pixel_mask[
                patch_index,
                time_index
            ] = item[
                'valid_mask'
            ]


            time_mask[
                patch_index,
                time_index
            ] = 1.0


            observation_valid_fraction[
                patch_index,
                time_index
            ] = item[
                'valid_fraction_colab'
            ]


            current_date = (
                pd.to_datetime(
                    date
                )
            )


            if last_date is None:

                delta_days[
                    patch_index,
                    time_index,
                    0
                ] = 0.0

            else:

                delta_days[
                    patch_index,
                    time_index,
                    0
                ] = (
                    current_date
                    - last_date
                ).days


            last_date = (
                current_date
            )

            patch_observation_count += 1


        if patch_observation_count == 0:

            raise RuntimeError(
                'No usable 2024 observations '
                f'for patch {patch_id}.'
            )


    # ---------------------------------------------------
    # Replace NO_DATA with zero only after masks exist
    # ---------------------------------------------------

    X[
        X == NO_DATA_VALUE
    ] = 0.0


    n_observations = (
        time_mask
        .sum(
            axis=1
        )
        .astype(
            np.int16
        )
    )


    return {
        'X':
            X,

        'y':
            y,

        'time_mask':
            time_mask,

        'valid_pixel_mask':
            valid_pixel_mask,

        'observation_valid_fraction':
            observation_valid_fraction,

        'delta_days':
            delta_days,

        'n_observations':
            n_observations,

        'patch_ids':
            np.array(
                patch_list
            ),

        'dates':
            np.array(
                date_list
            ),

        'bands':
            np.array(
                ALL_FEATURE_BANDS
            )
    }


test_2024_data = (
    build_2024_test_tensor()
)


print(
    '\nFinal tensor shapes:'
)

for key in [
    'X',
    'y',
    'time_mask',
    'valid_pixel_mask',
    'observation_valid_fraction',
    'delta_days',
    'n_observations',
    'patch_ids',
    'dates',
    'bands'
]:

    print(
        f'{key}:',
        test_2024_data[
            key
        ].shape
    )


print(
    '\nObservations per patch:',
    test_2024_data[
        'n_observations'
    ].min(),
    '-',
    test_2024_data[
        'n_observations'
    ].max()
)

print(
    'Mean observations:',
    test_2024_data[
        'n_observations'
    ].mean()
)

"""### 19.7 — Integrity checks before saving"""

# -------------------------------------------------------
# 19.7 Verify the 2024 tensor before saving
# -------------------------------------------------------

X_2024 = test_2024_data[
    'X'
]

y_2024 = test_2024_data[
    'y'
]

time_mask_2024 = test_2024_data[
    'time_mask'
]

valid_pixel_mask_2024 = test_2024_data[
    'valid_pixel_mask'
]

valid_fraction_2024 = test_2024_data[
    'observation_valid_fraction'
]

delta_days_2024 = test_2024_data[
    'delta_days'
]

n_observations_2024 = test_2024_data[
    'n_observations'
]

patch_ids_2024 = test_2024_data[
    'patch_ids'
].astype(str)

dates_2024 = test_2024_data[
    'dates'
].astype(str)

bands_2024 = test_2024_data[
    'bands'
].astype(str)


# -------------------------------------------------------
# Shape and identity checks
# -------------------------------------------------------

assert X_2024.shape[0] == 30

assert y_2024.shape == (
    30,
    50,
    50
)

assert X_2024.shape[-1] == 9

assert np.array_equal(
    patch_ids_2024,
    reference_patch_ids
)

assert np.array_equal(
    y_2024,
    reference_labels
)

assert bands_2024.tolist() == (
    ALL_FEATURE_BANDS
)


# -------------------------------------------------------
# Temporal checks
# -------------------------------------------------------

assert np.array_equal(
    time_mask_2024
    .sum(
        axis=1
    )
    .astype(
        np.int16
    ),
    n_observations_2024
)

assert all(
    pd.Timestamp(str(date)).year == 2024
    for date in dates_2024
)

assert np.all(
    delta_days_2024
    >= 0
)

assert np.isfinite(
    delta_days_2024
).all()


# -------------------------------------------------------
# Missing-data checks
# -------------------------------------------------------

missing_dates_2024 = (
    time_mask_2024
    == 0
)

assert np.all(
    valid_fraction_2024[
        missing_dates_2024
    ]
    == 0
)


missing_indices = np.argwhere(
    missing_dates_2024
)

for patch_index, time_index in (
    missing_indices[:50]
):

    assert np.all(
        X_2024[
            patch_index,
            time_index
        ]
        == 0
    )


# -------------------------------------------------------
# Valid-pixel fraction consistency
# -------------------------------------------------------

recomputed_valid_fraction = (
    valid_pixel_mask_2024
    .mean(
        axis=(
            2,
            3
        )
    )
)

available_dates_2024 = (
    time_mask_2024
    == 1
)

assert np.allclose(
    recomputed_valid_fraction[
        available_dates_2024
    ],
    valid_fraction_2024[
        available_dates_2024
    ],
    atol=1e-6
)


# -------------------------------------------------------
# Numerical checks
# -------------------------------------------------------

assert np.isfinite(
    X_2024
).all()

assert set(
    np.unique(
        y_2024
    ).tolist()
).issubset({
    0,
    1,
    2,
    3,
    255
})


print(
    '2024 tensor integrity checks passed.'
)

print(
    'Patch identity with 2023: EXACT'
)

print(
    'Reference labels identical to 2023: EXACT'
)

print(
    '2024 dates:',
    dates_2024[0],
    'to',
    dates_2024[-1]
)

print(
    'Global temporal dimension:',
    len(
        dates_2024
    )
)

print(
    'Observation range:',
    int(
        n_observations_2024.min()
    ),
    '-',
    int(
        n_observations_2024.max()
    )
)

"""### 19.8 — Save final 2024 cache"""

# -------------------------------------------------------
# 19.8 Save final 2024 temporal-transfer cache
# -------------------------------------------------------

np.savez_compressed(
    TEST_2024_CACHE_PATH,

    X=test_2024_data[
        'X'
    ],

    y=test_2024_data[
        'y'
    ],

    time_mask=test_2024_data[
        'time_mask'
    ],

    valid_pixel_mask=test_2024_data[
        'valid_pixel_mask'
    ],

    observation_valid_fraction=(
        test_2024_data[
            'observation_valid_fraction'
        ]
    ),

    delta_days=test_2024_data[
        'delta_days'
    ],

    n_observations=test_2024_data[
        'n_observations'
    ],

    patch_ids=test_2024_data[
        'patch_ids'
    ],

    dates=test_2024_data[
        'dates'
    ],

    bands=test_2024_data[
        'bands'
    ],

    split=np.array(
        'test'
    ),

    year=np.array(
        2024,
        dtype=np.int16
    ),

    months=np.array(
        MONTHS_2024,
        dtype=np.int16
    ),

    min_valid_fraction=np.array(
        MIN_VALID_FRACTION,
        dtype=np.float32
    ),

    reference_source=np.array(
        'ESA WorldCover 2021 via frozen 2023 Region B cache'
    )
)


print(
    'Saved:',
    TEST_2024_CACHE_PATH
)

print(
    'Exists:',
    TEST_2024_CACHE_PATH.exists()
)

print(
    'Compressed size MB:',
    TEST_2024_CACHE_PATH.stat().st_size
    / 1024**2
)

"""### 19.9 — Reload and compare 2023 vs 2024 Region B caches"""

# -------------------------------------------------------
# 19.9 Final reload and cross-year consistency check
# -------------------------------------------------------

REQUIRED_CACHE_KEYS = [
    'X',
    'y',
    'time_mask',
    'valid_pixel_mask',
    'observation_valid_fraction',
    'delta_days',
    'n_observations',
    'patch_ids',
    'dates',
    'bands'
]


def load_cache_for_comparison(path):
    with np.load(
        path,
        allow_pickle=False
    ) as npz_file:

        missing_keys = [
            key
            for key in REQUIRED_CACHE_KEYS
            if key not in npz_file.files
        ]

        if missing_keys:
            raise KeyError(
                f'Missing cache keys: {missing_keys}'
            )

        return {
            key: npz_file[key]
            for key in npz_file.files
        }


cache_2023_test = load_cache_for_comparison(
    TEST_2023_CACHE_PATH
)

cache_2024_test = load_cache_for_comparison(
    TEST_2024_CACHE_PATH
)


# -------------------------------------------------------
# Basic shapes
# -------------------------------------------------------

print('2023 X:', cache_2023_test['X'].shape)
print('2024 X:', cache_2024_test['X'].shape)

print('2023 y:', cache_2023_test['y'].shape)
print('2024 y:', cache_2024_test['y'].shape)

print(
    '2023 temporal dimension:',
    len(cache_2023_test['dates'])
)

print(
    '2024 temporal dimension:',
    len(cache_2024_test['dates'])
)


# -------------------------------------------------------
# Spatial/reference identity
# -------------------------------------------------------

patch_ids_2023 = (
    cache_2023_test['patch_ids']
    .astype(str)
)

patch_ids_2024 = (
    cache_2024_test['patch_ids']
    .astype(str)
)


assert np.array_equal(
    patch_ids_2023,
    patch_ids_2024
)

assert np.array_equal(
    cache_2023_test['y'],
    cache_2024_test['y']
)

assert np.array_equal(
    cache_2023_test['bands'].astype(str),
    cache_2024_test['bands'].astype(str)
)


# -------------------------------------------------------
# Observation statistics
# -------------------------------------------------------

comparison_rows = []

for year, data in [
    (2023, cache_2023_test),
    (2024, cache_2024_test)
]:

    n_obs = data[
        'n_observations'
    ].astype(int)

    dates = np.asarray(
        data['dates']
    ).astype(str)

    positive_delta = data[
        'delta_days'
    ][
        data['delta_days'] > 0
    ]

    comparison_rows.append({
        'year': year,
        'patches': len(
            data['patch_ids']
        ),
        'global_dates': len(
            dates
        ),
        'first_date': str(
            dates[0]
        ),
        'last_date': str(
            dates[-1]
        ),
        'min_observations': int(
            n_obs.min()
        ),
        'mean_observations': float(
            n_obs.mean()
        ),
        'median_observations': float(
            np.median(n_obs)
        ),
        'max_observations': int(
            n_obs.max()
        ),
        'mean_positive_delta_days': (
            float(
                positive_delta.mean()
            )
            if positive_delta.size
            else np.nan
        ),
        'max_positive_delta_days': (
            float(
                positive_delta.max()
            )
            if positive_delta.size
            else np.nan
        )
    })


cross_year_cache_summary = pd.DataFrame(
    comparison_rows
)

display(
    cross_year_cache_summary
)


# -------------------------------------------------------
# Final numerical integrity checks
# -------------------------------------------------------

for year, data in [
    (2023, cache_2023_test),
    (2024, cache_2024_test)
]:

    assert np.isfinite(
        data['X']
    ).all()

    assert np.isfinite(
        data['delta_days']
    ).all()

    assert np.array_equal(
        data['time_mask']
        .sum(axis=1)
        .astype(np.int16),

        data['n_observations']
        .astype(np.int16)
    )

    print(
        f'{year} cache integrity: PASSED'
    )


print(
    '\nPatch identity across years: EXACT'
)

print(
    'Reference labels across years: EXACT'
)

print(
    'Feature order across years: EXACT'
)

print(
    '\n2024 temporal-transfer cache is model-ready.'
)